apiVersion: apps/v1
kind: Deployment
metadata:
  name: akhq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: akhq
  template:
    metadata:
      labels:
        app: akhq
    spec:
      containers:
        - name: akhq
          image: tchiotludo/akhq:latest
          ports:
            - containerPort: 8083
          env:
            - name: AKHQ_CONFIGURATION
              value: |
                akhq:
                  connections:
                    kafka-cluster:
                      properties:
                        bootstrap.servers: "kafka:9092,kafka-broker2:9093"
            - name: MICRONAUT_SERVER_PORT
              value: "8083" # Wymuszenie nasłuchu na porcie 8083 bo domyslnie na 8080
---
apiVersion: v1
kind: Service
metadata:
  name: akhq
spec:
  selector:
    app: akhq
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  type: LoadBalancer
