apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-broker2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-broker2
  template:
    metadata:
      labels:
        app: kafka-broker2
    spec:
      containers:
        - name: kafka
          image: bitnami/kafka:latest
          ports:
            - containerPort: 9093 # Ustaw inny port dla nowego brokera
          env:
            - name: KAFKA_CFG_BROKER_ID
              value: "2" # Broker ID musi być unikalny
            - name: KAFKA_CFG_LISTENERS
              value: "PLAINTEXT://:9093"
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka-broker2:9093"
            - name: KAFKA_CFG_ZOOKEEPER_CONNECT
              value: "zookeeper:2181"
            - name: ALLOW_PLAINTEXT_LISTENER
              value: "yes"
          volumeMounts:
            - mountPath: /bitnami/kafka/data
              name: kafka-broker2-data
      volumes:
        - name: kafka-broker2-data
          persistentVolumeClaim:
            claimName: kafka-broker2-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-broker2
spec:
  ports:
    - port: 9093
      targetPort: 9093
  selector:
    app: kafka-broker2
  type: LoadBalancer
