apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-broker2-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/kafka-broker2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-broker2-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
