services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: microappdb
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  google-search-adapter:
    build:
      context: ./google-search-adapter
      dockerfile: Dockerfile
    image: alekosszu/microapp-google-search-adapter:latest
    container_name: google-search-adapter
    ports:
      - "8081:8081"
    depends_on:
      - mysql

  scheduler-service:
    build:
      context: ./scheduler-service
      dockerfile: Dockerfile
    image: alekosszu/microapp-scheduler-service:latest
    container_name: scheduler-service
    ports:
      - "8082:8082"
    depends_on:
      - mysql
      - mongo

  search-service:
    build:
      context: ./search-service
      dockerfile: Dockerfile
    image: alekosszu/microapp-search-service:latest
    container_name: search-service
    ports:
      - "8080:8080"
    depends_on:
      - mysql

volumes:
  mysql_data:
  mongo_data:
